### ISSUE TITLE
[main page] first iteration

### ISSUE THREAD

**Issue by FrancescoCioria** [sawsanias/gh-explorer#1]
## requirements

scope of the iteration:
- implement the page layout
  - nav bar
    - left: app name
    - center: search component
    - right: empty
  - results panel
    - should be a floating panel
## sub-issues
- [x] main layout structure #2 
- [x] implement NavBar #3 
- [x] implement ResultsPanel #4 
- [x] implement ResultsPanel scroll #12
## mockup

![image](https://cloud.githubusercontent.com/assets/4029499/12507566/d5aacfac-c0f6-11e5-8ed4-ed8411e97214.png)

**Comment by FrancescoCioria** [comment]
@sawsanias This is the beginning of our conversation about this "macro" issue. Fell free to post here your thoughts!

**Comment by FrancescoCioria** [comment]
@sawsanias ^

**Comment by giogonzo** [comment]
🎱
