### ISSUE TITLE
implement NavBar

### ISSUE THREAD

**Issue by FrancescoCioria** [sawsanias/gh-explorer#3]
<- #1 
## requirements
- left: the app name (GH-Explorer? you can choose!)
- right: nothing
- center: `SearchBar`
  - composed by one `input` and one `button`
  - should notify parent with new `value` when user clicks on button
- UI
  - content `max-width: 1000px`
  - you can style the rest as you wish (`background-color`, `height` ....)
## specs
- use `NavBar` (https://github.com/buildo/react-components/tree/master/src/nav-bar)

**Comment by giogonzo** [comment]
closed by #10
